version: 1.2
workflows:
   - name: GRAPE simulation
     subclass: CWL
     publish: true
     primaryDescriptorPath: /workflows/preprocess2/cwl/simulation.cwl
     testParameterFiles:
      - /workflows/preprocess2/cwl/config.json