name: Simulate

on:
  pull_request:
    branches: [ master ]
    
jobs:
  run_simulate:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    outputs:
      id: ${{ steps.simulation.outputs.funnel_id }}
    steps:
    - uses: actions/checkout@v2
    #- name: Install SSH Key
    #  uses: shimataro/ssh-key-action@v2
    #  with:        
    #    name: genx_github
    #    key: ${{ secrets.FUNNEL_SSH_PRIVATE }}
    #    known_hosts: placeholder
    #    
    #- name: Adding known hosts
    #  run: ssh-keyscan -H ${{ secrets.FUNNEL_HOST }} >> ~/.ssh/known_hosts
    #  
    - name: Call simulation
      id: simulation
      run: |
        f_id=$(sshpass -p '${{ secrets.FUNNEL_PASS }}' ssh ${{ secrets.FUNNEL_USER }}@${{ secrets.FUNNEL_HOST }} "bash -s" < simulation.sh "${{ github.event.pull_request.head.repo.git_url }}" "${{ github.head_ref }}" "${{ github.event.pull_request.head.sha }}" | awk 'END {print $NF}')
        echo $f_id
        echo "::set-output name=funnel_id::$f_id"
      
  send_message:
    runs-on: ubuntu-latest
    needs: run_simulate
    steps:
    - uses: actions/checkout@v2
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          Simulation status can be viewed here: http://${{ secrets.FUNNEL_HOST }}:8000/tasks/${{ needs.run_simulate.outputs.id }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
    
  slack_notification:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: github
        SLACK_MESSAGE: |
          'Pull request by ${{ github.event.sender.login }} opened: ${{ github.event.pull_request.html_url }}'
        SLACK_USERNAME: GitHub Pull Request Report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      
